// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPorts():Promise<Array<string>>;

export function StartEmission(arg1:string,arg2:number,arg3:Array<string>,arg4:number):Promise<void>;

export function StopEmission():Promise<void>;
