// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPorts() {
  return window['go']['main']['App']['GetPorts']();
}

export function StartEmission(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartEmission'](arg1, arg2, arg3, arg4);
}

export function StopEmission() {
  return window['go']['main']['App']['StopEmission']();
}
